import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'AbTechZone',
  description: 'Generated by AbTechZone',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
      {/* <link href="https://fonts.googleapis.com/css2?family=Afacad&family=Hind+Madurai:wght@300&family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200&family=Poppins&family=Roboto+Condensed:wght@300&family=Source+Sans+3:wght@400;600;700&display=swap" rel="stylesheet" /> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
